#SPDX-License-Identifier: MIT-0
---
# tasks file for ludice_setup

- name: Install or update dependencies
  ansible.builtin.apt:
    name:
      - nginx
      - php
      - php-cli
      - php-mbstring
      - php-xml
      - php-bcmath
      - php-curl
      - php-mysql
      - php-zip
      - php-tokenizer
      - php-common
      - php-json
      - php-readline
      - php-pgsql
      - php-fpm
      - composer
      - nodejs
      - npm
    state: latest
    install_recommends: false
    update_cache: true

- name: Create ludice directory
  ansible.builtin.file:
    name: "{{ ludice_setup_path }}"
    owner: "{{ ludice_setup_user }}"
    group: "{{ ludice_setup_user }}"
    state: directory

- name: Create symlink
  ansible.builtin.file:
    src: "{{ ludice_setup_deployer_path }}"
    path: "{{ ludice_setup_symlink }}"
    owner: "{{ ludice_setup_user }}"
    group: "{{ ludice_setup_user }}"
    force: true
    state: link

- name: Setup database user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ ludice_db_user }}"
    password: "{{ ludice_db_password }}"
    state: present

- name: Create database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ ludice_db_name }}"
    owner: "{{ ludice_db_user }}"
    state: present

- name: Install Certbot
  community.general.snap:
    name: certbot
    classic: true

- name: Delete default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Nginx ludice config
  ansible.builtin.template:
    src: nginx-ludice.conf.j2
    dest: /etc/nginx/sites-available/nginx-ludice.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Check server config exists
  ansible.builtin.stat:
    path: /etc/nginx/sites-available/ludice
  register: st

- name: Nginx server config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/ludice
    owner: root
    group: root
    mode: '0644'
  when: not st.stat.exists
  notify: Restart nginx

- name: Create nginx symlink
  ansible.builtin.file:
    src: /etc/nginx/sites-available/ludice
    dest: /etc/nginx/sites-enabled/ludice
    owner: root
    group: root
    state: link

- name: Certbot
  ansible.builtin.shell:
    cmd: |
      certbot --nginx \
              --non-interactive \
              --agree-tos \
              --redirect \
              --email 'support@ludice.app' \
              --domains {{ ludice_server_url }}
    creates: "/etc/letsencrypt/live/{{ ludice_server_url }}"
