#SPDX-License-Identifier: MIT-0
---
# tasks file for ludice_setup

- name: Install or update dependencies
  ansible.builtin.apt:
    name:
      - nginx
      - php
      - php-cli
      - php-mbstring
      - php-xml
      - php-bcmath
      - php-curl
      - php-mysql
      - php-zip
      - php-tokenizer
      - php-common
      - php-json
      - php-readline
      - php-pgsql
      - php-fpm
      - composer
      - nodejs
      - npm
    state: latest
    install_recommends: false
    update_cache: true

- name: Create ludice directory
  ansible.builtin.file:
    name: "{{ ludice_setup_path }}"
    owner: ludice
    group: ludice
    state: directory

# - name: Setup repository
#   become: true
#   become_user: ludice
#   ansible.builtin.git:
#     repo: "{{ ludice_setup_repository }}"
#     dest: "{{ ludice_setup_path }}/app"
#     version: "{{ ludice_setup_branch }}"

- name: Create symlink
  ansible.builtin.file:
    src: "{{ ludice_setup_path }}/app/current/public"
    dest: "{{ ludice_setup_symlink }}"
    owner: ludice
    group: ludice
    state: link

- name: Nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/ludice
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

# TODO:
# setup db user and db password and db name
# setup certbot & install
# add github actions keys
