---
# tasks file for data_disk

- name: Data ext4 partition
  community.general.filesystem:
    fstype: ext4
    resizefs: true
    dev: "{{ data_disk_src }}"

- name: Mount and bind volume
  ansible.posix.mount:
    path: "{{ data_disk_mount }}"
    src: "{{ data_disk_src }}"
    opts: defaults
    state: mounted
    fstype: ext4
    backup: true

- name: Allow user to create directory in data disk
  ansible.builtin.file:
    name: "{{ data_disk_mount }}"
    owner: "{{ ludice_setup_user }}"
    group: "{{ ludice_setup_user }}"
    mode: "0777"
    state: directory
